version: '3'
services:
  app:
    container_name: node-mongo
    restart: always
    build: .
    # default image name: master_app
    image: spcity/node-mongo-app:latest
    volumes:
      # for aws (has /etc/letsencrypt)
      - /etc/letsencrypt:/etc/letsencrypt
      
      # for local (no /etc/letsencrypt)
      - ./letsencrypt:/usr/src/app/letsencrypt
    ports:
      - '80:3000'
      - '443:443'
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:4
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'